runtime: nodejs20

default_expiration: '2d'

env_variables:
  NUXT_PUBLIC_APP_ENV: $NUXT_PUBLIC_APP_ENV
  DEFAULT_DOMAIN: $DEFAULT_DOMAIN
  NUXT_PUBLIC_BASE_URL: $NUXT_PUBLIC_BASE_URL
  NUXT_PUBLIC_GOOGLE_SITE_VERIFICATION: $NUXT_PUBLIC_GOOGLE_SITE_VERIFICATION
  NUXT_PUBLIC_GTAG_ID: $NUXT_PUBLIC_GTAG_ID
  NUXT_API_KEY: $NUXT_API_KEY
  NUXT_AUTH_DOMAIN: $NUXT_AUTH_DOMAIN
  NUXT_PROJECT_ID: $NUXT_PROJECT_ID
  NUXT_STORAGE_BUCKET: $NUXT_STORAGE_BUCKET
  NUXT_MESSAGING_SENDER_ID: $NUXT_MESSAGING_SENDER_ID
  NUXT_APP_ID: $NUXT_APP_ID
  NUXT_MEASUREMENT_ID: $NUXT_MEASUREMENT_ID
  NUXT_PUBLIC_OFFLINE_MODE: $NUXT_PUBLIC_OFFLINE_MODE
  NUXT_PUBLIC_API_BASE_PATH: $NUXT_PUBLIC_API_BASE_PATH
  NUXT_SITEMAP_SOURCE_URL=: $NUXT_SITEMAP_SOURCE_URL

handlers:
  - url: /favicon.ico
    static_files: public/favicon.ico
    upload: public/favicon.ico
    expiration: '365d'
  - url: /seo.webp
    static_files: public/seo.webp
    upload: public/seo.webp
    expiration: '365d'
  - url: /.*
    script: auto
    secure: always
    redirect_http_response_code: 301
