runtime: nodejs20

default_expiration: "1d"

env_variables:
  APP_ENV: $APP_ENV
  DEFAULT_DOMAIN: $DEFAULT_DOMAIN
  NUXT_PUBLIC_BASE_URL: $NUXT_PUBLIC_BASE_URL
  NUXT_PUBLIC_GOOGLE_SITE_VERIFICATION: $NUXT_PUBLIC_GOOGLE_SITE_VERIFICATION
  NUXT_PUBLIC_GTAG_ID: $NUXT_PUBLIC_GTAG_ID
  NUXT_API_KEY: $NUXT_API_KEY
  NUXT_AUTH_DOMAIN: $NUXT_AUTH_DOMAIN
  NUXT_PROJECT_ID: $NUXT_PROJECT_ID
  NUXT_STORAGE_BUCKET: $NUXT_STORAGE_BUCKET
  NUXT_MESSAGING_SENDER_ID: $NUXT_MESSAGING_SENDER_ID
  NUXT_APP_ID: $NUXT_APP_ID
  NUXT_MEASUREMENT_ID: $NUXT_MEASUREMENT_ID
  NUXT_PUBLIC_OFFLINE_MODE: $NUXT_PUBLIC_OFFLINE_MODE

handlers:
  - url: /_nuxt/.*
    secure: always
    http_headers:
      X-Author: "anirbmuk (github.com/anirbmuk)"
  - url: /.*
    script: auto
    secure: always
    redirect_http_response_code: 301
