runtime: nodejs22

default_expiration: '2d'

automatic_scaling:
  max_instances: 1

env_variables:
  NUXT_PUBLIC_APP_ENV: $NUXT_PUBLIC_APP_ENV
  DEFAULT_DOMAIN: $DEFAULT_DOMAIN
  NUXT_PUBLIC_BASE_URL: $NUXT_PUBLIC_BASE_URL
  NUXT_PUBLIC_GOOGLE_SITE_VERIFICATION: $NUXT_PUBLIC_GOOGLE_SITE_VERIFICATION
  NUXT_PUBLIC_GTM_ID: $NUXT_PUBLIC_GTM_ID
  NUXT_PUBLIC_GTM_DEBUG: $NUXT_PUBLIC_GTM_DEBUG
  NUXT_PUBLIC_GTM_ENABLED: $NUXT_PUBLIC_GTM_ENABLED
  NUXT_FIREBASE_API_KEY: $NUXT_FIREBASE_API_KEY
  NUXT_FIREBASE_AUTH_DOMAIN: $NUXT_FIREBASE_AUTH_DOMAIN
  NUXT_FIREBASE_PROJECT_ID: $NUXT_FIREBASE_PROJECT_ID
  NUXT_FIREBASE_STORAGE_BUCKET: $NUXT_FIREBASE_STORAGE_BUCKET
  NUXT_FIREBASE_MESSAGING_SENDER_ID: $NUXT_FIREBASE_MESSAGING_SENDER_ID
  NUXT_FIREBASE_APP_ID: $NUXT_FIREBASE_APP_ID
  NUXT_FIREBASE_MEASUREMENT_ID: $NUXT_FIREBASE_MEASUREMENT_ID
  NUXT_PUBLIC_OFFLINE_MODE: $NUXT_PUBLIC_OFFLINE_MODE
  NUXT_PUBLIC_API_BASE_PATH: $NUXT_PUBLIC_API_BASE_PATH
  NUXT_SITEMAP_SOURCE_URL: $NUXT_SITEMAP_SOURCE_URL
  NUXT_REDIS_HOST: $NUXT_REDIS_HOST
  NUXT_REDIS_PORT: $NUXT_REDIS_PORT
  NUXT_REDIS_PREFIX: $NUXT_REDIS_PREFIX

handlers:
  - url: /.*
    script: auto
    secure: always
    redirect_http_response_code: 301
