name: web-profile repo pull-requests

on:
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22.14.0

      - name: Cache node_modules
        id: cache-node-modules-pre
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-build-web-profile-node-modules-${{ hashFiles('yarn.lock') }}

      - name: Install node_modules
        if: steps.cache-node-modules-pre.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile

  build:
    needs: [install]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22.14.0
      - uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-build-web-profile-node-modules-${{ hashFiles('yarn.lock') }}

      - name: Build web-profile project
        run: yarn build

      - name: Lint web-profile project
        run: yarn lint
