name: web-profile repo branch-merges

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.10.0

      - name: Cache node_modules
        id: cache-node-modules-pre
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-build-web-profile-node-modules-${{ hashFiles('yarn.lock') }}

      - name: Install node_modules
        if: steps.cache-node-modules-pre.outputs.cache-hit != 'true'
        run: yarn install

  build:
    needs: [install]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.10.0
      - uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-build-web-profile-node-modules-${{ hashFiles('yarn.lock') }}

      - name: Build web-profile project
        run: yarn build

      - name: Lint web-profile project
        run: yarn lint

      - name: Archive build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-compiled
          path: .output

  deploy:
    name: deploy
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: dist-compiled
          path: .output
      - uses: golang-enthusiast/app-yaml-env-compiler@v1.0
        env:
          NUXT_PUBLIC_APP_ENV: ${{ secrets.NUXT_PUBLIC_APP_ENV }}
          DEFAULT_DOMAIN: ${{ secrets.DEFAULT_DOMAIN }}
          NUXT_PUBLIC_BASE_URL: ${{ secrets.NUXT_PUBLIC_BASE_URL }}
          NUXT_PUBLIC_GOOGLE_SITE_VERIFICATION: ${{ secrets.NUXT_PUBLIC_GOOGLE_SITE_VERIFICATION }}
          NUXT_PUBLIC_GTAG_ID: ${{ secrets.NUXT_PUBLIC_GTAG_ID }}
          NUXT_FIREBASE_API_KEY: ${{ secrets.NUXT_FIREBASE_API_KEY }}
          NUXT_FIREBASE_AUTH_DOMAIN: ${{ secrets.NUXT_FIREBASE_AUTH_DOMAIN }}
          NUXT_FIREBASE_PROJECT_ID: ${{ secrets.NUXT_FIREBASE_PROJECT_ID }}
          NUXT_FIREBASE_STORAGE_BUCKET: ${{ secrets.NUXT_FIREBASE_STORAGE_BUCKET }}
          NUXT_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.NUXT_FIREBASE_MESSAGING_SENDER_ID }}
          NUXT_FIREBASE_APP_ID: ${{ secrets.NUXT_FIREBASE_APP_ID }}
          NUXT_FIREBASE_MEASUREMENT_ID: ${{ secrets.NUXT_FIREBASE_MEASUREMENT_ID }}
          NUXT_PUBLIC_OFFLINE_MODE: ${{ secrets.NUXT_PUBLIC_OFFLINE_MODE }}
          NUXT_PUBLIC_API_BASE_PATH: ${{ secrets.NUXT_PUBLIC_API_BASE_PATH }}
          NUXT_SITEMAP_SOURCE_URL: ${{ secrets.NUXT_SITEMAP_SOURCE_URL }}

      - id: 'auth'
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Deploy to GCP
        run: |
          cd ${{ github.workspace }}
          yarn deploy:gae
